# Generated by Django 3.0.3 on 2020-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_currensy'),
    ]

    operations = [
        migrations.CreateModel(
            name='XTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Currensy',
            new_name='CCurrensy',
        ),
    ]
