# Generated by Django 3.0.3 on 2020-05-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200511_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, unique=True, verbose_name='Наименование Полное'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=120, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='short_name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Наименование Краткое'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='УНП'),
        ),
    ]
