# Generated by Django 3.0.3 on 2020-05-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200517_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Валюта')),
                ('sign', models.CharField(max_length=5, unique=True, verbose_name='Обозначение')),
            ],
        ),
        migrations.DeleteModel(
            name='CCurrensy',
        ),
        migrations.DeleteModel(
            name='XTest',
        ),
    ]
