# Generated by Django 3.0.3 on 2020-05-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200517_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curr',
            new_name='Currensy',
        ),
    ]
