# Generated by Django 3.0.3 on 2020-05-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200512_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Наименование Полное'),
        ),
    ]
