# Generated by Django 3.0.3 on 2020-05-18 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200517_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmt_type', models.CharField(choices=[('every_time', 'Каждый раз по безналу'), ('once_a_month', 'Раз в месяц'), ('cash', 'черех кассу'), ('other', 'другое')], default='other', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.Currensy'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pmt_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='customers.Payment_Types'),
        ),
    ]
