# Generated by Django 3.0.3 on 2020-05-18 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200518_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pmt_type',
            field=models.ForeignKey(default='BYN', on_delete=django.db.models.deletion.CASCADE, to='customers.Payment_Types'),
        ),
    ]
