# Generated by Django 3.0.3 on 2020-05-19 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20200518_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='customers.Currensy'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pmt_type',
            field=models.ForeignKey(default='cash', on_delete=django.db.models.deletion.CASCADE, to='customers.Payment_Types'),
        ),
    ]
