# Generated by Django 3.0.3 on 2020-05-24 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0010_auto_20200519_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_date_start', models.DateField(auto_now=True, verbose_name='Дата')),
                ('volume', models.FloatField(verbose_name='Объем')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Заказчик')),
            ],
        ),
    ]
