# Generated by Django 3.0.3 on 2020-05-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_order',
            name='cleaning_date_start',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
