# Generated by Django 3.0.3 on 2020-05-31 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_orders', '0003_auto_20200530_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_order',
            name='cleaning_date_start',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 11, 16, 47, 677875), verbose_name='Дата'),
        ),
    ]
