# Generated by Django 3.0.3 on 2020-06-01 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_orders', '0004_auto_20200531_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_order',
            name='cleaning_date_start',
            field=models.DateField(default=datetime.datetime(2020, 6, 1, 7, 15, 17, 112229), verbose_name='Дата'),
        ),
    ]
