# Generated by Django 3.0.3 on 2020-05-13 13:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tank_Num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Trail_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_type', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_date_start', models.DateField(auto_now=True, verbose_name='Дата')),
                ('cleaning_date_end', models.DateField(verbose_name='Дата окончания')),
                ('cleaning_time_start', models.TimeField(verbose_name='Время начала')),
                ('cleaning_time_end', models.TimeField(verbose_name='Время окончания')),
                ('external_cleaning', models.BooleanField(verbose_name='Наружная мойка')),
                ('internal_cleaning', models.BooleanField(verbose_name='Внутренняя мойка цистерны')),
                ('steaming', models.TimeField(verbose_name='пропарка, ч')),
                ('sec1', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)])),
                ('sec2', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)])),
                ('sec3', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)])),
                ('sec4', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)])),
                ('sec5', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)])),
                ('sec6', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)])),
                ('add_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Add_work', verbose_name='Доп работы')),
                ('car_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Car_Num', verbose_name='Номер машины')),
                ('car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Car_Type')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Заказчик')),
                ('driver_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Driver', verbose_name='Водитель')),
                ('tank_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Tank_Num', verbose_name='Номер полуприцепа/контейнера')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Team', verbose_name='Смена')),
                ('trail_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Trail_Type')),
            ],
        ),
    ]
