# Generated by Django 3.0.3 on 2020-05-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_auto_20200511_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_date_start', models.DateField(verbose_name='Дата')),
                ('cleaning_date_end', models.DateField(verbose_name='Дата окончания')),
                ('cleaning_time_start', models.TimeField(verbose_name='Время начала')),
                ('cleaning_time_end', models.TimeField(verbose_name='Время окончания')),
                ('external_cleaning', models.BooleanField(verbose_name='Наружная мойка')),
                ('internal_cleaning', models.BooleanField(verbose_name='Внутренняя мойка цистерны')),
                ('steaming', models.TimeField(verbose_name='пропарка, ч')),
                ('add_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Add_work')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Заказчик')),
                ('driver_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Driver', verbose_name='Водитель')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Team', verbose_name='Смена')),
            ],
        ),
    ]
