# Generated by Django 3.0.3 on 2020-05-12 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='sec1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='sec2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='sec3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='sec4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='sec5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='sec6',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='add_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Add_work', verbose_name='Доп работы'),
        ),
    ]
