# Generated by Django 3.0.3 on 2020-05-12 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200512_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='sec1',
            field=models.FloatField(default=0, max_length=5, validators=[django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='sec2',
            field=models.FloatField(default=0, max_length=5, validators=[django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='sec3',
            field=models.FloatField(default=0, max_length=5, validators=[django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='sec4',
            field=models.FloatField(default=0, max_length=5, validators=[django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='sec5',
            field=models.FloatField(default=0, max_length=5, validators=[django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='sec6',
            field=models.FloatField(default=0, max_length=5, validators=[django.core.validators.MaxValueValidator(40)]),
        ),
    ]
