# Generated by Django 3.0.3 on 2020-05-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200513_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='steaming',
            field=models.TimeField(verbose_name='пропарка, ч'),
        ),
    ]
