# Generated by Django 3.0.3 on 2020-05-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='add_work',
            name='work',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='car_num',
            name='num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car_type',
            name='car_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tank_num',
            name='num',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='trail_type',
            name='trail_type',
            field=models.CharField(max_length=30),
        ),
    ]
