# Generated by Django 3.0.3 on 2020-05-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200515_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='registry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Order_registry', verbose_name='Журнал моек'),
        ),
    ]
