# Generated by Django 3.0.3 on 2020-05-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='desinfection',
            field=models.BooleanField(default=False, verbose_name='Дезинфекция'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
